---
- name: playbook to install generic tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    TFROM: 1.8.5
  tasks:
    - name: check hostname
      shell: cat /etc/iso-release
    - name: perform update
      shell: apt-get update
    - name: install tools
      shell: apt-get install -y unzip jq stress net-tools
      



